### ISSUE TITLE
00_Introduction.mdの誤字脱字、表記ゆれ

### ISSUE THREAD

**Issue by gacky35** [i13302/ISSUE-Linux-Root-Expr#10]
## 影響度(1:続行不可,2:講義で説明,3:気づかないかも)
3

## 内容
誤字脱字、表記ゆれ

## 場所(ファイル名と行番号)
11, 16: 情報システム･セキュリティ実験1の表記ゆれ
49: 各個人 重言 普通使わないように思う。他のところでは"各自"と書いている
53: 不自然 それらについてのサポートを教員やTAは十分にできないことを… みたいな感じにしたほうが自然に思う

**Comment by i13302** [comment]
> 11, 16: 情報システム･セキュリティ実験1の表記ゆれ

先生「授業名はちゃんと書こう」
ぼく「ローマ数字が授業名であること自体がおかしい」
の結果なので，保留
