### ISSUE TITLE
Root-02 /etc/group ファイルの中身について

### ISSUE THREAD

**Issue by hishibiro** [i13302/ISSUE-Linux-Root-Expr#26]
## 影響度(1:続行不可,2:講義で説明,3:気づかないかも)
3
## 内容
```
/etc/group ファイル
(~省略~)
adm:x:4:kida
(~省略~)
wheel:x:10:itakehara
(~省略~)
itakehara:x:1000:itakehara
teacher:x:1001:
student:x:1002:kida
```
---
/etc/passwdと/etc/groupより以下がわかる．
    ・itakehara はUID1000で，主グループはGID1000の itakehara に所属しており，サブグループは
    GID10のwheelに所属している．
    ・kida はUID1001で，主グループはGID1001の teacher に所属しており，サブグループはGID4の
    adm とGID1002の student に所属している．
    ・ikejiri は，UID1002で，主グループは，GID1002の student に所属している．
なお，/etc/groupの4フィールド目(GIDの後ろ)には，サブグループとして所属するユーザ名が記述されて
いる．
主グループは，/etc/passwdで確認する．

→ /etc/group ファイルの中身とkida,ikejiriの解説されている中身と合わないと思います。

## 場所(ファイル名と行番号など．わかりやすく)
Root-02_User-Manage.pdf p11

**Comment by i13302** [comment]
>  /etc/group ファイルの中身とkida,ikejiriの解説されている中身と合わないと思います。

どこが合わないのか書いてくれるとありがたい．

**Comment by hishibiro** [comment]
useraddで追加したアカウントの主グループ表示の仕様でした。解決しました。
